# Generated by Django 3.2 on 2021-04-12 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210412_1903'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('heading', models.CharField(max_length=200, unique=True)),
                ('pro_image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('short_intro', models.TextField()),
                ('twitter_link', models.CharField(blank=True, max_length=200, null=True)),
                ('linkedin_link', models.CharField(blank=True, max_length=200, null=True)),
                ('github_link', models.CharField(blank=True, max_length=200, null=True)),
                ('stackoverflow_link', models.CharField(blank=True, max_length=200, null=True)),
                ('codepen_link', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='post',
            name='post_image',
        ),
        migrations.AddField(
            model_name='post',
            name='post_banner',
            field=models.ImageField(blank=True, null=True, upload_to='images/banners'),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_thum',
            field=models.ImageField(blank=True, null=True, upload_to='images/thumbnails'),
        ),
    ]
