# Generated by Django 3.2 on 2021-04-30 10:31

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_post_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_thum',
            field=models.ImageField(blank=True, null=True, upload_to='images/thumbnails//%Y/%m/%d/'),
        ),
    ]
